file_name = input("Enter fileName:")
fp = open(file_name, 'w+')
fp.write("cat\n")
fp.write("dog\n")
fp.write("bear\n")
fp.write("hello\n")
fp.write("elephant\n")
fp.write("hello\n")
fp.write("tiger\n")
fp.write("hello\n")
fp.write("horse\n")
fp.seek(0)
i = fp.readlines()
#print(i)
fp = open(file_name, 'r+')
fp.truncate(0)
fp = open(file_name, 'w')
for d in i:
    if d != "hello\n":
        fp.write(d)